### ISSUE TITLE
SQL file missing

### ISSUE THREAD

**Issue by userMacieG** [ElPumpo/esx#4]

**Comment by iSentrie** [comment]
https://github.com/esx-framework/es_extended/blob/v1-final/es_extended.sql

**Comment by userMacieG** [comment]
> https://github.com/esx-framework/es_extended/blob/v1-final/es_extended.sql

Nope, this is not correct database for now. 
For right now I see 2 new types of data:
`health` and `armour`

**Comment by userMacieG** [comment]
Also `group` is now `groups`
